"""Toolchain writer module — Generate .anima/toolchain.toml from detection results.

Converts DetectionResult into TOML configuration that the kernel executes
generically. See CONTRACT.md for the interface and SPEC.md for format details.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from domain.models import DetectionResult, ToolchainEntry

logger = logging.getLogger("anima.toolchain_writer")

_HEADER = "# Generated by anima init — edit freely.\n"


def _escape_toml_string(value: str) -> str:
    """Escape a string for TOML double-quoted representation."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _entry_to_toml(entry: ToolchainEntry) -> str:
    """Serialize a single ToolchainEntry to a TOML ``[[toolchain]]`` section."""
    lines = [
        "[[toolchain]]",
        f'path = "{_escape_toml_string(entry.path)}"',
        f'stack = "{_escape_toml_string(entry.stack)}"',
        f'lint = "{_escape_toml_string(entry.lint)}"',
        f'typecheck = "{_escape_toml_string(entry.typecheck)}"',
        f'test = "{_escape_toml_string(entry.test)}"',
        f'coverage = "{_escape_toml_string(entry.coverage)}"',
    ]
    return "\n".join(lines)


def generate_toml(result: DetectionResult) -> str:
    """Generate TOML content from detection results.

    Pure function — no file I/O. Returns a valid TOML string that can
    be parsed by ``tomllib.loads()``.

    Args:
        result: Detection result from init_detector.detect().

    Returns:
        Complete TOML string with trailing newline.
    """
    sections = [_HEADER]
    for entry in result.entries:
        sections.append(_entry_to_toml(entry))
    return "\n".join(sections) + "\n"


def write_toolchain(result: DetectionResult, anima_dir: str) -> str:
    """Write toolchain.toml to the given .anima/ directory.

    Creates the directory if it does not exist.

    Args:
        result: Detection result from init_detector.detect().
        anima_dir: Absolute path to the ``.anima/`` directory.

    Returns:
        Absolute path of the written file.
    """
    dir_path = Path(anima_dir)
    dir_path.mkdir(parents=True, exist_ok=True)

    toml_path = dir_path / "toolchain.toml"
    content = generate_toml(result)
    toml_path.write_text(content, encoding="utf-8")

    logger.info("Wrote toolchain config to %s", toml_path)
    return str(toml_path.resolve())
